# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VivadoProjects/Nexys-4-DDR-Master.xdc

# IP: ip/TriangleFifo/TriangleFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TriangleFifo || ORIG_REF_NAME==TriangleFifo} -quiet] -quiet
