webtalk_init -webtalk_dir C:/Users/wille/Desktop/Data_D/VivadoProjects/LFSR/LFSR.sim/sim_1/behav/xsim/xsim.dir/TB_LFSR16_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 28 12:22:20 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "adc6426d-0244-4bd8-9b77-0986a9fe81fd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "863bfdadcb0144e2bffeda7af2f9fced" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "45" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "12020 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6008_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3107807210 -regid "" -xml C:/Users/wille/Desktop/Data_D/VivadoProjects/LFSR/LFSR.sim/sim_1/behav/xsim/xsim.dir/TB_LFSR16_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/wille/Desktop/Data_D/VivadoProjects/LFSR/LFSR.sim/sim_1/behav/xsim/xsim.dir/TB_LFSR16_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/wille/Desktop/Data_D/VivadoProjects/LFSR/LFSR.sim/sim_1/behav/xsim/xsim.dir/TB_LFSR16_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
