# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config  -ruleid {1}  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design roodScherm has port VGA_G[3] driven by constant 0}}  -suppress 
set_msg_config  -ruleid {2}  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design roodScherm has port VGA_G[2] driven by constant 0}}  -suppress 
set_msg_config  -ruleid {3}  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design roodScherm has port VGA_G[1] driven by constant 0}}  -suppress 
set_msg_config  -ruleid {4}  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design roodScherm has port VGA_G[0] driven by constant 0}}  -suppress 
set_msg_config  -ruleid {5}  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design roodScherm has port VGA_B[3] driven by constant 0}}  -suppress 
set_msg_config  -ruleid {6}  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design roodScherm has port VGA_B[2] driven by constant 0}}  -suppress 
set_msg_config  -ruleid {7}  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design roodScherm has port VGA_B[1] driven by constant 0}}  -suppress 
set_msg_config  -ruleid {8}  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design roodScherm has port VGA_B[0] driven by constant 0}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.cache/wt} [current_project]
set_property parent.project_path {C:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.srcs/sources_1/new/roodScherm.vhd}}
read_ip -quiet {{C:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.srcs/constrs_1/imports/VivadoProjects/Nexys-4-DDR-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/wille/Desktop/Data D/VivadoProjects/rood_scherm/rood_scherm.srcs/constrs_1/imports/VivadoProjects/Nexys-4-DDR-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top roodScherm -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef roodScherm.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file roodScherm_utilization_synth.rpt -pb roodScherm_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
